### ISSUE TITLE
allow to compute 'next version' even when HEAD is on a version tag

### ISSUE THREAD

**Issue by McFoggy** [jgitver/jgitver#106]
as it is requested in jgitver/jgitver-maven-plugin#134, jgitver/jgitver-maven-plugin#132, jgitver/jgitver-maven-plugin#56 we should provide a mean of computing the 'next' version even when HEAD is on a version tag:
- automatically if in a dirty state : ie someone started to work for next version even without committing new stuff
- by a flag to force computation of 'next version'

This way, if we consider a repository, checkout on master branch tagged with `1.0.0`
Using a maven mode without using dirty state:
- without modification: jgitver will return `1.0.0`
- with some modification: jgitver will return `1.0.1-SNAPSHOT`
- without modification but a force flag: jgitver will return `1.0.1-SNAPSHOT`

**Comment by vadipp** [comment]
Hi Matthieu!

>automatically if in a dirty state : ie someone started to work for next version even without committing new stuff

Is it possible to allow this behaviour in "pattern" strategy, not only "maven" strategy?

I've already integrated your awesome plugin in our build pipelines using "pattern" strategy, however this particular case slipped my attention. In our workflow it's common to just push a fresh branch from master and add a dependency on the resulting SNAPSHOT version even before any new commits are pushed to that branch.

**Comment by vadipp** [comment]
I just realized that my case requires the version to be computed as snapshot even if the repo is not dirty, but merely because of the fact that a non-master branch is currently checked out (even if the branch points to a tagged commit). Is such thing possible? :thinking:
