### ISSUE TITLE
jgitver used in a monorepo?

### ISSUE THREAD

**Issue by altfatterz** [jgitver/jgitver#111]
Hi,

I am wondering about using jgitver in a monorepo approach.
Do you think is good idea? Do you have any examples?

**Comment by McFoggy** [comment]
It depends on what you mean by monorepo.
Do you consider that all your projects/components share the same version?
Do you release them all in one shoot or not. If not do you need continuity in version numbering (acceptable to have projectx-1.1.0 followed by projectx-1.4.0 without 2 & 3 for example)
Do your components share the same technology stack.

Finally I would just say if it suits your needs then use it ! have fun 😉
