### ISSUE TITLE
Improved version numbers for release branches / wild cards in nonQualifierBranches

### ISSUE THREAD

**Issue by jschneider** [jgitver/jgitver#12]
Release branches following GitFlow are named like that:
release/1.0.0

This results in an ugly version: 1.0.0-release_1.0.0-SNAPSHOT

Solution 1:
Allow wildcards in nonQualifierBranches. E.g. "<nonQualifierBranches>master, develop,release/*</nonQualifierBranches>

Solution 2:
Somehow magically identify the duplicate 1.0.0 and avoid it:
Resulting version number: 1.0.0-release-SNAPSHOT

**Comment by McFoggy** [comment]
relates to #5 & #6
