### ISSUE TITLE
Support branchPolicy regex with mutually exclusive capture groups

### ISSUE THREAD

**Issue by drekbour** [jgitver/jgitver#123]
The following regex has two mutually-exclusive capture groups 

    <pattern>(?:hotfix|feature)/(?:(\w{3,}-[0-9]+).*|(.*))</pattern>

This matches either of
* feature/TICKET-123_description > (TICKET-123, null)
* feature/description > (null, description)

1.7.1 fails this on the second case because `group(1)` is null.

Workaround is to have two carefully-ordered `branchPolicies` with the same `transformation`s (which is a DRY fail)

**Comment by McFoggy** [comment]
the pattern supports only one capturing group.

can't you reverse the capturing/non-capturing ?  with `( (?:xxx) | (?:yyy) )`

**Comment by drekbour** [comment]
Wonderful idea but only works where the content is a full match.

    (?:hotfix|feature)/((?:\w{3,}-[0-9]+).*|(?:.*))
                                         ^^
    
This no longer extracts the ticket because the trailing part is part of the capture
* :x: feature/TICKET-123_description > TICKET-123_description

The ask is that the pattern supports one _non-null_ capture-group. My example was specifically crafted to be exclusively one or the other.

**Comment by McFoggy** [comment]
we should investigate how breaking/compatible it would be to enhance the rule from "1 capturing group" to "first non null/not empty capturing group"

**Comment by drekbour** [comment]
Should be fine because it isn't an enforced rule! The provided pattern has two groups and works just fine in the TICKET case.
The current rule takes group(1) without checking for others. If group(1) is null, the tool fails. Hence, all existing users have a working group(1) and this change is as extension not change to that support
