### ISSUE TITLE
Auto increment a release for major, minor and patch?

### ISSUE THREAD

**Issue by dev-samples** [jgitver/jgitver#129]
Based on :

https://github.com/jgitver/jgitver#release

I create a new release using something like:

`git tag -a -m "release 4.1.1, additional reason" 4.1.1`

But I don't really care about specifying exact versions through an annotated tag each time I want to make a release.

Ideally I just want to specify _major_ or _minor_ and _patch_ and then **jgitver** should automatically compute the next version number based on a previous tag.

As an example, assume the latest tag is: **4.1.1** then I just want to specify `./gradlew releasePatch` and as a result a new tag is created with version **4.1.2**. Similar if I instead run `./gradlew releaseMinor` a tag with version **4.2.0** is created,

Is that possible?

Or is it necessary to specify the full version each time a new release needs to be created?

**Comment by McFoggy** [comment]
https://github.com/jgitver/jgitver#release paragraph describes only the way jgitver itself is released.

> But I don't really care about specifying exact versions through an annotated tag each time I want to make a release.

It is unfortunate because jgitver is fully based on analyzing tags...

> Ideally I just want to specify major or minor and patch and then jgitver should automatically compute the next version number based on a previous tag.

jgitver exposes the computed next [Major, MInor and Patch](https://github.com/jgitver/jgitver/blob/master/src/main/java/fr/brouillard/oss/jgitver/metadata/Metadatas.java#L127-L138) versions as metadatas. You could use that to automatically tag your code base if you want inside your own tasks like `releaseMinor` or `releasePatch`.

**Comment by dev-samples** [comment]
Sorry for not being clear, I am fan of **jgitver** being tag based! Its just that 9/10 times I just need a new release with the patch version being incremented and it would be easier to just fire off some utils task: `releasePatch` instead of looking up the previous tag and typing in the correct x.y.z+1 each time.

I think its actually the same that is being discussed here: https://github.com/jgitver/jgitver/issues/39#issuecomment-747155778

Regarding 
https://github.com/jgitver/jgitver/blob/f02ab852cb8409fd01eb47e9cdd6b3655fde1fb7/src/main/java/fr/brouillard/oss/jgitver/metadata/Metadatas.java#L127-L138

that's really cool and based on:

https://github.com/jgitver/gradle-jgitver-plugin#metadatas

I just created a small test tasks that prints what I need:

```
task releaseDummy() {
    doFirst {
        println "$project.ext.git_sha1_full" 
        println "$project.ext.next_major_version"
    }
}
```

**Comment by McFoggy** [comment]
glad you found what you needed
