### ISSUE TITLE
Metadatas.NEXT_PATCH_VERSION behaves different/wrong on CI

### ISSUE THREAD

**Issue by dev-samples** [jgitver/jgitver#130]
UPDATE: Works as expected, ignore/delete below. 

Based on:
https://github.com/jgitver/jgitver/blob/f02ab852cb8409fd01eb47e9cdd6b3655fde1fb7/src/main/java/fr/brouillard/oss/jgitver/metadata/Metadatas.java#L138

I have created the following tasks in my **build.gradle** file:

```
task releasePatch() {
    doFirst {
        println "$project.ext.next_patch_version"
    }
}
```

When I build locally with e.g.:

`./gradlew releasePatch`

I get:

_> Task :releasePatch
2.3.5_

Which is correct since my last tag is **2.3.4**. 

But when I run the exact same task from Jenkins I get:

```
21:59:33  + ./gradlew releasePatch
21:59:34  Starting a Gradle Daemon, 1 incompatible and 3 stopped Daemons could not be reused, use --status for details
21:59:42  
21:59:42  > Task :releasePatch
21:59:42  0.0.1
```

Which is wrong.

Based on:

https://github.com/jgitver/gradle-jgitver-plugin#building-on-detached-head

in my Jenkins pipeline I have also tried:

`sh "./gradlew releasePatch -Djgitver.branch=master"`

Any suggestions?

**Comment by McFoggy** [comment]
Take care in CI on how you checkout the code.

jgitver, generally speaking, needs:
- the tags to be fetched
- enough commit history
- branch information
- ...

checkouting just the commit (which is the default on most CI) is probably not what users will expect.

Glad you found a solution by yourself.
