### ISSUE TITLE
Fail release if annotated tag already exists (no changes since last release)?

### ISSUE THREAD

**Issue by dev-samples** [jgitver/jgitver#132]
Based on:

https://jgitver.github.io/

> maven release with jgitver is reduced to the following
> 
> git tag -a X.Y.Z
> mvn deploy
> 

I am releasing my (gradle) projects using jgitver and it works fine. 

I have a few corner cases one of them being how to prevent a release to be performed if tip of the branch to release already contains an annotated tag (no changes have been made since last release).

Without adding some additional (clutter) logic jgitver will simply create a new annotated tag and I will get new artifacts with the new version (supplied automatically using `project.ext.next_patch_version`) even though nothing has changed.

Is there some simple function/variable in jgitver I have missed that I can use to make this check before proceeding with release or do I need to implement my own clutter/boilerplate for this?

**Comment by McFoggy** [comment]
Hello

> jgitver will simply create a new annotated tag

Not at all ; jgitver does not tag anything. It is up to you to tag your git repository in the way you want.

By combining `git tag --list` & `git cat-file` you can probably check what you want.

Some inspiration:

````
~/my-project# git log --oneline
084b19d (HEAD -> dev, tag: v0.0.1, tag: 1.0.0) add command 1

~/my-project# git for-each-ref refs/tags
89c35afd57fbe9cb60d1d63fd658b22b4cb0ce34 tag    refs/tags/1.0.0                              <-- Annotated
084b19d52b9cf614b588d19e8fdcda9621a9ecd2 commit refs/tags/v0.0.1                       <-- Lightweight

~/my-project# git cat-file -t 1.0.0
tag
~/my-project# git cat-file -t v0.0.1
commit
````

You could then just script your tag creation suing something like:
````
~/my-project# ((git tag --list --points-at HEAD | xargs -I %s git cat-file -t %s | grep tag > /dev/null) && echo Annotated tag found on HEAD) || echo No annotated tag found on HEAD
Annotated tag found on HEAD
````

**Comment by dev-samples** [comment]
Sorry of course its my task that currently creates the tag not jgitver! :-)

Thanks for the example and clarifying that is not the purpose/responsibility of jgitver - which I kinda assumed.
