### ISSUE TITLE
maven-mode but with a twist

### ISSUE THREAD

**Issue by davidkarlsen** [jgitver/jgitver#135]
I like the defaults in maven-mode, but is it possible to get the default maven strategy, just with short git-sha added?

I.e. on my feature branch it would not be:
```
10.4.16-SNAPSHOT -> 10.4.16-feature_jgitver-SNAPSHOT
```

but:
```
10.4.16-SNAPSHOT -> 10.4.16-<thesha>-feature_jgitver-SNAPSHOT
```
?

I tried adding:
```
cat .mvn/jgitver.config.xml 
<configuration xmlns="http://jgitver.github.io/maven/configuration/1.1.0"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://jgitver.github.io/maven/configuration/1.1.0 https://jgitver.github.io/maven/configuration/jgitver-configuration-v1_1_0.xsd">
    <useCommitDistance>true</useCommitDistance>
</configuration>
```

or 
```
cat .mvn/jgitver.config.xml 
<configuration xmlns="http://jgitver.github.io/maven/configuration/1.1.0"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://jgitver.github.io/maven/configuration/1.1.0 https://jgitver.github.io/maven/configuration/jgitver-configuration-v1_1_0.xsd">
    <useGitCommitId>true</useGitCommitId>
</configuration>
```

but still the same.

**Comment by davidkarlsen** [comment]
It seems others have this wish too: https://stackoverflow.com/questions/49452765/jgitver-maven-plugin-derive-version-from-git-commit-including-git-sha8-strin

**Comment by McFoggy** [comment]
David, as I said on SO what is the need behind having the sha1 in the version for SNAPSHOTs, I do not get the point.

**Comment by McFoggy** [comment]
if you want a different version for each commit, then do not use the maven policy.

**Comment by davidkarlsen** [comment]
> David, as I said on SO what is the need behind having the sha1 in the version for SNAPSHOTs, I do not get the point.

That's what I was wondering - the maven scheme is not tweakable, right?

**Comment by twogee** [comment]
Maven versions have a [specification](https://books.sonatype.com/mvnref-book/reference/pom-relationships-sect-pom-syntax.html). The point is that only versions that follow the specification can be resolved by Maven. Is your Git history so volatile, that you need a commit hash in Maven classifier? This is not what classifier is intended for - the POM specification states: "The classifier distinguishes artifacts that were built from the same POM but differ in content. "

**Comment by davidkarlsen** [comment]
I agree - we're a bit atypical here, because it's maven projects, which produce docker-images, and we require these to have immutable tagging, and set the deployment plugin to not deploy any jars, hence we're not that interested in the whole maven thing - so then we simply go the route of a custom strategy.

Thanks for the responses.
