### ISSUE TITLE
Hotfix Releases and version calculation

### ISSUE THREAD

**Issue by jschneider** [jgitver/jgitver#14]
I am playing around with a repository using GitFlow.

After a hotfix release the version on the development branch is calculated from the hotfix tag and not the lightweight tag further down.

Sample:
https://github.com/jschneider/jgitver-playing-ground/commit/fc773bb320b9fcc7ac877e70d65b9ae8a8ca63af

When checking out this commit on develop, jgitver returns "1.0.2-SNAPSHOT" as version.
I would prefer "1.1.0-SNAPSHOT".

I understand why the version "1.0.2-SNAPSHOT" is calculated. But maybe there is a better way to calculate that?

In this case there are two possible tags that could be used as base for calculations: 1.0.1 and 1.1.0-SNAPSHOT.
I think 1.1.0-SNAPSHOT should be used, because:
- both tags come from different lines (there is a merge commit)
- 1.1.0-SNAPSHOT has the larger version number

**Comment by jschneider** [comment]
This is especially important since I can't create the 1.1.0-SNAPSHOT tag again...

**Comment by jschneider** [comment]
Yes. Moving the tag is possible. This has two downsides:
- I have to do a "git push --tags --force" which will affect my collegues
- The version number for the already existing commits changes (since the old tag is removed).

Therefore I don't think that moving the tag is a good idea.

**Comment by McFoggy** [comment]
> moving the tag is a good idea.
This is the difference, at least how I see it, between lightweight & annotated tags ; and this is one of the features that makes jgitver power.
For sure annotated tags MUST never be moved, but lightweights...
Honestly I am not sure a declarative way of versioning like jgitver will be possible to cover all cases if it is not allowed to do some tricks like that.

**Comment by McFoggy** [comment]
as jgtiver is currently based on tag usage & lightweigth tag move I close this issue. Open a RFE if it cannot suit your needs.

**Comment by sunlixia** [comment]
why can't we simply compare the lightweight tag and annotated tag, if lightweight tag is "bigger", use it. Eg. if v1.1.0 and 1.0 both exiting, use v1.1.0 and build 1.1.0-snapshot
