### ISSUE TITLE
Need a 'QUALIFIED_DIRTY' meta field to use in versionPattern definitions

### ISSUE THREAD

**Issue by kebeda** [jgitver/jgitver#143]
Given a versionPattern definition as follows:
```
<versionPattern>${M}.${m}.${meta.COMMIT_DISTANCE}${-~meta.QUALIFIED_BRANCH_NAME}${-~meta.DIRTY}</versionPattern>
```
building on a branch **feat/optimize-parsing** yields:
```
demo 0.1.3-feat_optimize_parsing-false
```
when the commit is clean, and:
```
demo 0.1.3-feat_optimize_parsing-true
```
when the commit is dirty.

In order to maintain the previous behavior, I would like a new metadata setting `${meta.QUALIFIED_DIRTY}` (or whatever you deem fit) that would behave as follows when put into the versionPattern definition string:
```
<versionPattern>${M}.${m}.${meta.COMMIT_DISTANCE}${-~meta.QUALIFIED_BRANCH_NAME}${-~meta.QUALIFIED_DIRTY}</versionPattern>
```
```
demo 0.1.3-feat_optimize_parsing
```
when the commit is clean, and:
```
demo 0.1.3-feat_optimize_parsing-dirty
```
when the commit is dirty.

If it isn't obvious at this point, I would like a way to append the word "dirty" to the version only when dirty is true, instead of "true/false", depending on the state of dirty.

Thank you.

**Comment by McFoggy** [comment]
isn't [Metadatas.DIRTY_TEXT](https://github.com/jgitver/jgitver/blob/c7895668a5f27389bf208139fc565defdb64fd78/src/main/java/fr/brouillard/oss/jgitver/metadata/Metadatas.java#L37) what you are looking for?

**Comment by kebeda** [comment]
Absolutely! This is _exactly_ what I was looking for, thank you. Before I close this, can we add this to the "Meta fields" table at https://jgitver.github.io/#_gradle_configuration? I had assumed the documentation was up to date with the code...

**Comment by kebeda** [comment]
See: https://github.com/jgitver/jgitver.github.io/pull/4

**Comment by McFoggy** [comment]
thanks
