### ISSUE TITLE
support gitflow branching model

### ISSUE THREAD

**Issue by McFoggy** [jgitver/jgitver#15]
Several RFE relate to better branch handling.

As gitflow is a popular branching model, jgitver should adapt and provide (1) a support & if possible (2) a seemless, easy & out the box usage.

see also jgitver/jgitver-maven-plugin#16

**Comment by jraduget** [comment]
Could you advice providing a jgitver config example to enable git-flow basics branching model: develop / release / feature ... on a simple maven project? I spent several night hours without any success looking for google, github, commits above... trying different strategy with or without jgitver.config.xml... without success. My environment is macOS 11.4, maven 3.6.x, adoptOpenJdk 8. I realise issue is many more on jgitver-maven-plugin project, but if you can advice me, many thanks!
