### ISSUE TITLE
Allow for the "-g" prefix to be part of the generated version number

### ISSUE THREAD

**Issue by eduardozamin** [jgitver/jgitver#24]
## Background

When using `git describe` to describe a commit, git adds the `-g` prefix to the commit hash:
```
$ git describe --tags --long
1.0.1-7-ge24b4ac
       ^^
```
What's interesting about using this format is that the whole string generated by `git describe` can be directly used for a checkout command:
```
$ git checkout 1.0.1-7-ge24b4ac
Note: checking out '1.0.1-7-ge24b4ac'.
You are in 'detached HEAD' state. You can look around, make experimental
...
HEAD is now at e24b4ac...
```

If the `-g` prefix is ommited, the checkout will not work:
```
$ git checkout 1.0.1-7-e24b4ac
error: pathspec '1.0.1-7-e24b4ac' did not match any file(s) known to git.
```

## Feature Request

It would be nice if **jgitver** (and related plugins -- e.g. I'm using the [jgitver-maven-plugin](https://github.com/jgitver/jgitver-maven-plugin)) allows for generating the commit hash with the `-g` prefix in it. 
This would allow a developer to always be able to checkout a given "version number", without having to care if this is a major tag, a minor tag, or just a commit in between.

Currently this is not possible; the "commit-hash" part of the version number does not contain the `-g` prefix.

Current behaviour:
```
$ mvn compile
...
[INFO] ------------------------------------------------------------------------
[INFO] Building module-xyz 1.0.1-7-a21b55ae
[INFO] ------------------------------------------------------------------------
[INFO] 
```

Desired behaviour:
```
$ mvn compile
...
[INFO] ------------------------------------------------------------------------
[INFO] Building module-xyz 1.0.1-7-ga21b55ae
[INFO] --------------------------- ^ ------------------------------------------
[INFO]                             |
```

**Comment by McFoggy** [comment]
I wasn't aware of this feature ; might be used to ensure that nobody moves/rewrites an annotated tag _(which should never happen of course)_.

**Comment by McFoggy** [comment]
@eduardozamin can you please verify in the branch `long-tag` _(badly named ;-) )_ that the behavior is the one you expected?
To simplify the verification process, execute the following command:  
`mvn clean test -Dtest=Scenario8WithLongFormatTest -Djgitver.debug=true` 
It will run the created TestCase but will not remove the created git directory on disk. The test will output the location on your disk

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running fr.brouillard.oss.jgitver.strategy.configurable.others.Scenario8WithLongFormatTest
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

git repository created under: D:\Users\awxgx\.babun\cygwin\tmp\1488922776158-0\.git

Tests run: 11, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.575 sec
```

Then just use you shell, cd there and play with git checkout and git describe.

**Comment by eduardozamin** [comment]
Hi @McFoggy , thanks!
I'm able to run the tests and I do not see anything strange with the directory created with it. But I'm not sure I understand what you mean by running `git describe: this means calling `git` directly so obviously it works.

Is there any way I can invoke jgitver from the command line? (sorry, Java newbie here)

**Comment by McFoggy** [comment]
sorry I wasn't very explicit.
I just mean't : _please try to do 2 things_:
- look at the JUnit test to verify that the feature corresponds to what you need/expect
- use the debug option and use the generated repository & git commands to help yourself in the verification process if needed

> I'm not a Java expert, so --> is there any way I can invoke jgitver from the command line?

unfortunately not but that would be interresting though

**Comment by eduardozamin** [comment]
Hi @McFoggy,

Before going into more details, I would like to first understand how **jgitver** works in "normal" mode (i.e. with `versionCalculator.setUseLongFormat(false)`).

I added some unit tests (https://github.com/jgitver/jgitver/pull/25) based on Scenario8WithLongFormatTest.java, which is based on "Scenario8":
```
$ git lg
** ba58bfe - (4 minutes ago) content F - Matthieu Brouillard (issue-10)
| * f79c238 - (4 minutes ago) content E - Matthieu Brouillard (HEAD -> master)
| * c8a6fb0 - (4 minutes ago) content D - Matthieu Brouillard (tag: 1.1.0)
|/
** 2a5bc65 - (4 minutes ago) content C - Matthieu Brouillard
** 3466319 - (4 minutes ago) content B - Matthieu Brouillard (tag: 1.0.0)
** d43eee1 - (4 minutes ago) content A - Matthieu Brouillard
```

I adapted the settings to reflect what I'm using, which is:
```
        versionCalculator.setMavenLike(false);
        versionCalculator.setAutoIncrementPatch(true);
        versionCalculator.setUseGitCommitId(true);
        versionCalculator.setUseLongFormat(false); // <--- not using long format yet
        versionCalculator.setGitCommitIdLength(8);
        versionCalculator.setUseDistance(false);
```

As you can see on the test results (https://travis-ci.org/jgitver/jgitver/builds/209761345), there are 3 errors:

```
Results :
Failed tests:   version_of_A_commit(fr.brouillard.oss.jgitver.strategy.configurable.others.Scenario8WithoutGPrefixCommitTest): (..)
  version_of_F_commit(fr.brouillard.oss.jgitver.strategy.configurable.others.Scenario8WithoutGPrefixCommitTest): (..)
  version_of_branch_issue_10(fr.brouillard.oss.jgitver.strategy.configurable.others.Scenario8WithoutGPrefixCommitTest): (..)
Tests run: 316, Failures: 3, Errors: 0, Skipped: 0
```

Here a better overview:
```
Test                          Expected                  Got                        Result
----------------------------- ------------------------- -------------------------- ------
version_of_A_commit           0.0.0-c7236b9e            0.0.0                        X
version_of_B_commit           1.0.0                     1.0.0                        OK
version_of_C_commit           1.0.1-fac7bd44            1.0.1-fac7bd44               OK
version_of_D_commit           1.1.0                     1.1.0                        OK
version_of_E_commit           1.1.0-e21b6dce            1.1.0-e21b6dce               OK
version_of_F_commit           1.0.2-3558cd25            1.0.1-3558cd25               X
version_of_annotated_tags     1.0.0                     1.0.0                        OK
version_of_light_tag_1_1_0    1.1.0                     1.1.0                        OK
version_of_master             1.1.0-e21b6dce            1.1.0-e21b6dce               OK
version_of_branch_issue_10    1.0.2-3558cd25-issue_10   1.0.1-3558cd25-issue_10      X
```

Could you explain why these 3 cases are failing? Either my understanding/expectation is incorrect, or there is an error.

Once that is clarified I would post a table here with the expected results for the case where `setUseLongFormat=true`.

**Comment by McFoggy** [comment]
Hi Eduardo,

for the failing tests:
- `version_of_F_commit` & `version_of_branch_issue_10` it is the expectations that are wrong ; base version for the calculation is the one found on B , ie `1.0.0` with patch incremented (as asked in the configuration) thus it should be `1.0.1` not `1.0.2` (followed by qualifiers of course).
- for `version_of_A_commit`, it is indeed a bug that comes from `VersionStrategy#isBaseCommitOnHead`.  
    this method works on head node & on the node where we stopped while finding the base version (normally a node with a tag). In the case of the first commit it is buggy because this node can have no tag ; this is the case in the example, default version `0.0.0` is used for node A.

I'll integrate your PR and correct the problem.

**Comment by eduardozamin** [comment]
Hi @McFoggy,
Regarding `version_of_F_commit`: I got a bit confused by the fact that - as you described it - it would have the same version as `version_of_C_commit` (except for the qualifier).
(This however has nothing to do with the issue being discussed here, I'll look at the code and see how it works)
Thanks!
