### ISSUE TITLE
NOT_DIRTY support

### ISSUE THREAD

**Issue by vromero** [jgitver/jgitver#27]
In maven there is not expression language and probably there will never be. The only very limited case of EL is in the profile activation.

Often times it is necessary to enabled or disable some plugins when the build is final. This could be done with the <skip></skip> configuration that is used to be found in the plugins or by using profiles.

JGitver works perfectly well with profiles as profiles can negate a boolean property. This said, the use of profiles is problematic in many cases because only one profile can be active at a time. JGitver can be used to disable some plugins on release like this:

```xml
<profiles>
        <profile>
            <id>non-dirty-build</id>

            <activation>
                <property>
                    <name>jgitver.dirty</name>
                    <value>!true</value>
                </property>
            </activation>

            <build>
                <plugins>
                    <plugin>
                        <groupId>my.org</groupId>
                        <artifactId>my-plugin</artifactId>
                        <configuration>
                          <skip>true</skip>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
```

But this would prevent the user to use its own profiles.

On the other hand, skip can be used directly without profiles. And JGitver already supports the case of disabling executions on dirty builds by : `<skip>${jgitver.dirty}</skip>`. But it is not possible to disable executions on not dirty builds as this is not possible in maven: `<skip>${!jgitver.dirty}</skip>`.

It would probably be advisable to have a NOT_DIRTY (just like there is a DIRTY) metadata for this cases.

**Comment by McFoggy** [comment]
Interresting idea. We could even probably go further by providing other explicit boolean properties but here I am not yet convinced that [jgitver](https://github.com/jgitver/jgitver) is the right place.  
I mean [jgitver](https://github.com/jgitver/jgitver) already exposes the positive version of the dirty state ; shouldn't it be up to the plugins _([jgitver_maven_plugin](https://github.com/jgitver/jgitver_maven_plugin) in this case)_ to expose the negation or any other usefull property?

**Comment by vromero** [comment]
That is a fair point. I'll rework.
