### ISSUE TITLE
Running jgitver should be optional

### ISSUE THREAD

**Issue by MattFriedman** [jgitver/jgitver#30]
If jgitver exists in the extensions.xml file, then it always runs, even if you are performing maven operations that don't require this versioning feature. 

So, I hope you can implement a flag such as perhaps `-Djgitver.versioning=true|false` so that we can run the plugin or not depending on what is appropriate at the time.

**Comment by McFoggy** [comment]
This issue was moved to jgitver/jgitver-maven-plugin#58
