### ISSUE TITLE
Allow `useGitCommitId` in `mavenLike` mode

### ISSUE THREAD

**Issue by vromero** [jgitver/jgitver#31]
One classic problem of maven is the inability to understand which version is currently deployed in a system when a SNAPSHOT is used.
One potential solution would be to use `useGitCommitId` but it is ignored when `mavenLike` mode is `true`. 

The alternative approach, to not to use the `mavenLike` mode, is not ideal as the `-SNAPSHOT` suffix has special connotations in maven and cannot be replaced by the non-configurable word `dirty`.

**Comment by McFoggy** [comment]
@vromero sorry but I do not understand what you want to achieve. If you want jgitver to add the commitId (which is unique) in the version as a qualifier then why should you append SNAPSHOT to that?  
If you want uniqueness just do not use mavenLike. Did I miss something?

**Comment by vromero** [comment]
Hi @McFoggy thanks for the quick reply,

You are right I could just not use mavenLike but `-SNAPSHOT` has special [semantics](https://docs.oracle.com/middleware/1212/core/MAVEN/maven_version.htm#MAVEN401) in Maven (specially repository wise, to maintain them small and tidy; also for instance to make sure that proxies and mirrors are not overly caching the -SNAPSHOTS as anything without that clasifier will be considered a release that wont change). 

I tried with `mavenLike` as `false` but the best I can get is a `-dirty` that doesn't enable the special semantics repository side. That is why I propose to enable `useGitCommitId` in `mavenLine` mode.

Although I might be wrong? Perhaps maven repositories won't detect two classifiers -asdf2134-SNAPSHOT?

**Comment by McFoggy** [comment]
feel free to reopen on purpose.

Although see #33 that could be of some benefits for your use case.

**Comment by vromero** [comment]
33# indeed superseeds this issue
