### ISSUE TITLE
Jenkinsfile checkout SCM leaves repo in detached head

### ISSUE THREAD

**Issue by Johnlon** [jgitver/jgitver#38]
... therefore the jgitver plugin refuses to add a branch name to the artifact I'd.

My Jenkins console says "obtaining jenkinsfile from [the hash]"

So my builds are always detached.

Does this plugin work with multi ranch pipelines?

Thanks

**Comment by Johnlon** [comment]
Thinking about this. If the problem is the Jenkins Gitscm.java then does that mean jgitver doesn't work on Jenkins at all??

**Comment by McFoggy** [comment]
It is the way you have configured your jenkins SCM that is wrong, see [this wiki page](https://github.com/jgitver/jgitver-maven-plugin/wiki/automatic-builds-for-maven%2C-jenkins-and-gitbucket) from the [jgitver-maven-plugin](https://github.com/jgitver/jgitver-maven-plugin) wiki.

**Comment by Johnlon** [comment]
Do you have a tested example using the  git as source rather than github?
I tried the closest thing I could to your web page but using git as source
and it doesn't work. I'm running bitbucket so I use but rather than github
as source.

**Comment by Johnlon** [comment]
Ok so I installed the bitbucket plugin to Jenkins and it supports those
options. But having tried this alternative I find that the checkout is
still on a commit and thus detached.

No luck.

**Comment by McFoggy** [comment]
@Johnlon in the wiki the other examples are using the simple git source, look at [jenkins-integration-multibranch-pipeline](https://github.com/jgitver/jgitver-maven-plugin/wiki/jenkins-integration-multibranch-pipeline).
Take care of the branch name as being `**`  otherwise SHA1 will be checked out.

**Comment by McFoggy** [comment]
please use the [gitter room](https://gitter.im/jgitver/Lobby) in case you need further help: https://gitter.im/jgitver/Lobby

**Comment by McFoggy** [comment]
@Johnlon even if I am not a big fan of it, as a follow up of #40, you can now specify a branch qualifier as a system property or as an environment variable
- using either `jgitver.branch` system property or `JGITVER_BRANCH` environment variable.

See https://github.com/jgitver/jgitver-maven-plugin#command-line-arguments or https://github.com/jgitver/gradle-jgitver-plugin#building-on-detached-head

**Comment by McFoggy** [comment]
reopen if required
