### ISSUE TITLE
Provide the branch or tag explicitly

### ISSUE THREAD

**Issue by jgsuess** [jgitver/jgitver#40]
Several CI servers use headless checkouts to ensure the precise specification of the version that is being used. The branch and tag information is offered separately, usually through an environment variable injected into the environment. This has the consequence that `jgitver` is not able to operate, unless a second checkout is used to provide the head reference and branch. This makes it impossible to use `jgitver` for automated feature branch builds, which is one of its main strengths.

This feature request asks for a means to specify the branch or tag explicitly, so that `jgitver` can operate as usual. The consistency between branch name and commit could be checked using the 
[List Branch](http://download.eclipse.org/jgit/site/4.11.0.201803080745-r/apidocs/org/eclipse/jgit/api/ListBranchCommand.html) Command.

**Comment by McFoggy** [comment]
@jgsuess what CI do you use? 

If you use Jenkins I have documented in [jgitver-maven-plugin](https://github.com/jgitver/jgitver-maven-plugin/wiki/automatic-builds-for-maven%2C-jenkins-and-gitbucket) how to checkout the branch instead of the commitID from webhook notification.

But I agree that it is a bit different to checkout a branch and to checkout a commit.

**Comment by jgsuess** [comment]
Here is the list of [Gitlab CI environment variables](https://docs.gitlab.com/ee/ci/variables/#predefined-variables-environment-variables). `CI` shows that it is a CI environment. Probing for `GITLAB_CI` shows that it is Gitlab CI. From there on, the variables can be queried.

BTW: `GitVersion`, a C# relative of `JGitVer` [had a similar issue with Jenkins](https://coderwall.com/p/3ipx_a/gitversion-it-looks-like-the-branch-being-examined-is-a-detached-head-on-jenkins) and responded with [this feature](https://github.com/GitTools/GitVersion/pull/326).

**Comment by McFoggy** [comment]
@jgsuess I verified again how Jenkins was doing the check-out, when setup to checkout using received branch name it ends with a command like:
`git checkout -b master a67c1ddb623f0b94d16dbbde76d824df386e086c`
which means that we have everything for jgitver:
- the good sha1
- the good branch

can't you configure gitlab to do the same?

**Comment by McFoggy** [comment]
by the way I just added a mean to externally provide a branch name when HEAD is detached.
You'll have to provide either:
- a system property: `jgitver.branch`
- an env variable: `JGITVER_BRANCH`

**Comment by jgsuess** [comment]
Sorry for being out of loop for so long. Just have returned to this and I am still unable to get jgitver to take the branch into account on detached head. I have provided both the environment variable and property, but it seems they are ignored. Is there a log setting that I can use to see if it is considering this and how it arrives at its result?

**Comment by McFoggy** [comment]
it was not released yet. I have just built `0.6.0`, once it is available in central, I'll publish also new versions for the maven & gradle plugins.

**Comment by jgsuess** [comment]
Oh great! We are setting up all our projects here for JGitVer. My boss
really liked it's features. Better and less bulky than Andromeda.

**Comment by McFoggy** [comment]
`jgitver-maven-plugin-1.3.0` is published at [sonatype](https://oss.sonatype.org/#nexus-search;gav~~jgitver-maven-plugin~1.3.0~~) and is on its way to [maven-central](http://search.maven.org/), just be patient for the replication (few minutes/hours normally)

> My boss really liked it's features

Which company? Oracle?  
Whatever company it is if you need more precise enhancements, feel free to contact me. 

Think also to spread the word and make some noise/buzz around the project ; I am definitively not good at marketing it so a tweet, post is always appreciated.

**Comment by jgsuess** [comment]
Will do that. And yes, we are using it in the Oracle Labs in Australia.

**Comment by jgsuess** [comment]
Just checked with the maven plugin and it does this implicitly now. This is great. Will the gradle plugin and also be republished? Thanks so much for this.

**Comment by McFoggy** [comment]
[gradle-jgitver-plugin](https://github.com/jgitver/gradle-jgitver-plugin) is now up to date in its latest [version](https://plugins.gradle.org/plugin/fr.brouillard.oss.gradle.jgitver) `0.4.1`

**Comment by jgsuess** [comment]
Can confirm that it works in the wild! Thank you for the great work.
