### ISSUE TITLE
Version matching regex should allow dot (.) in qualifier

### ISSUE THREAD

**Issue by JohnWu-Pro** [jgitver/jgitver#5]
Quote from semver,

> A pre-release version MAY be denoted by appending a hyphen and a series of dot separated identifiers immediately following the patch version. Identifiers MUST comprise only ASCII alphanumerics and hyphen [0-9A-Za-z-].

For example, `1.0.0-alpha.1` would be valid semver version, but won't match the current regex `v?([0-9]+(?:\.[0-9]+){0,2}(?:-[a-zA-Z0-9\-_]+)?)`. It may be corrected as `v?([0-9]+(?:\.[0-9]+){0,2}(?:-[a-zA-Z0-9\-\.]+)?)`, to allow dot (.) and disallow underscore.

**Comment by McFoggy** [comment]
I'll fix that together with #5 to be sure not to block users having '_' in their version naming.
