### ISSUE TITLE
maxVersion and lookup for tags in merged branches should be default behavior 

### ISSUE THREAD

**Issue by McFoggy** [jgitver/jgitver#53]
Current lookup of commits relies on a walk of all commits reachable from the `HEAD` without any control on how merge & parent commits are.
By default jgitver stops the lookup on the first encountered _version_ tag.

With #49 a new parameter controls, if jgitver stops or if continues the lookup to find other candidates _version_ tags ; choosing in the end the greatest found.

Instead of parsing the commits in a random order as it is today using the standard RevWalk, a better control of the graph parsing should be done and instead of stopping at the first tag encountered, jgitver should retrieve the first tag in each _branch_ it is able the reach from the `HEAD` and then keep only the greatest.

**Comment by McFoggy** [comment]
@djarosz what is your opinion?

**Comment by djarosz** [comment]
I think this behaviour would be more natural and easer to understand so I think it is good idea.

With current behaviour only the only way to backport some changes from other branches (i.e production branch fixes) without polluting version numbers (as it does in my current projects) is to do cherry-picking. Using simple 'git merge' in those situations would be more natural in my opinion.

But still changing default behaviour might (?) introduce some incompatibilities for current users.

**Comment by McFoggy** [comment]
> But still changing default behavior might introduce some incompatibilities for current users.

It might but I prefer to correct it right now instead of spreading a "bug feature".

I quickly implemented it this morning and all tests passed correctly ; I'll put the changes today later.
It has also the benefit that bringing it as a default does not require any of the plugins to implement additional behavior.

Thanks for your very quick feedback.

**Comment by djarosz** [comment]
Great. And of course after merging Your code my PR in plugin projects can be rejected.
