### ISSUE TITLE
introduce a lookup strategy

### ISSUE THREAD

**Issue by McFoggy** [jgitver/jgitver#70]
## Requirement

As a _project maintainer_ I would like to be able to configure jgitver strategy to find _version tags_ dependings on the project needs.

## Acceptance

- the following modes should be available:
  - `LATEST`: find the reachable version tag which has the most recent date
  - `NEAREST`: find the reachable version tag which is the nearest regarding current HEAD. In case several tags are found at the same depth, the one with the highest version will be kept.
  - `MAX`: find the reachable version tag which has the maximum version number
- default mode if not specified is `MAX`

**Comment by jschneider** [comment]
Thanks for releasing these changes. I gave it a try:

- no configuration: 2372ms --> tag with largest version number (as expected)
- Strategy: CONFIGURABLE, Policy: LATEST --> same result as without configuration
- Strategy: CONFIGURABLE, Policy: NEAREST --> 7618 ms --> tag as expected for nearest
- Strategy: CONFIGURABLE, Policy: LATEST --> java.lang.IllegalStateException: failure calculating version (https://github.com/jgitver/jgitver/issues/73)

Removing the "strategy"-tag doesn't seem to change anything. So I am not sure what the case for this is.


JGitver 1.3.0 takes about 2 secs in the same repository.
