### ISSUE TITLE
Bug calculating version

### ISSUE THREAD

**Issue by mbrasil** [jgitver/jgitver#75]
I'm having a bug in the latest jgitver version (0.10.2) in the following scenario:

I have two branches, master and develop. When I made a commit to the master branch and then tag it with "1.0.0" (it's the only tag that I have in the repository), later I cherry pick that commit to my develop branch. In develop, I ran "mvn validate" and gave me "0.0.0-develop-SNAPSHOT". I was expecting "1.0.1-SNAPSHOT". I was able to reproduce the error using the Katacoda maven demo (https://www.katacoda.com/mcfoggy/courses/jgitver/maven-intro) and adding the following code:

`git checkout -b develop`

`echo test > test.txt`

`git add . && git commit -m "test"`

`git checkout master`

`echo test2 > test2.txt
`git add . && git commit -m "test2"`

`git tag -d 1.0`
`git tag -a -m "test" 1.0.0 a06c5ae870c2a77387c3540c5cd25c9d18632990 (this hash is the test2 commit hash)`

`git checkout develop`

`git cherry-pick a06c5ae870c2a77387c3540c5cd25c9d18632990 (this hash is the test2 commit hash)`

`mvn validate`

I downloaded the source code for the project and I was able to fix the issue, but I don't know if its correct.

In fr.brouillard.oss.jgitver.impl.GitVersionCalculatorImpl.filterReachableTags, the RevWalk was not walking through all the branches to find the tags, only just the HEAD branch. If we change to this code, it works:

```java  
private List<Ref> filterReachableTags(ObjectId headId, List<Ref> allVersionTags) throws IOException {
	List<Ref> filtered = new ArrayList<>();

	Collection<Ref> allRefs = repository.getRefDatabase().getRefs();

	try (RevWalk walk = new RevWalk(repository)) {
	    walk.markStart(walk.parseCommit(headId));

	    for (Ref ref : allRefs) {
		walk.markStart(walk.parseCommit(ref.getObjectId()));
	    }

	    for (RevCommit revCommit : walk) {
		ObjectId commitId = revCommit.getId();
		Predicate<Ref> tagCorresponds = r -> commitId.getName().equals(refToObjectIdFunction.apply(r).getName());
		allVersionTags.stream().filter(tagCorresponds).forEach(filtered::add);
	    }
	}

	return filtered;
    }
```

And in fr.brouillard.oss.jgitver.impl.DistanceCalculator, the same thing:

```java
public Optional<Integer> distanceTo(ObjectId target) {
	    DepthWalk.RevWalk walk = null;
	    try {
		Collection<Ref> allRefs = repository.getRefDatabase().getRefs();

		walk = new DepthWalk.RevWalk(repository, maxDepth);
		RevCommit startCommit = walk.parseCommit(startId);
		walk.markRoot(startCommit);

		for (Ref ref : allRefs) {
		    walk.markRoot(walk.parseCommit(ref.getObjectId()));
		}

		walk.setRetainBody(false);

		Iterator<? extends RevCommit> commitIterator = walk.iterator();

		while (commitIterator.hasNext()) {
		    RevCommit commit = commitIterator.next();
		    if (commit.getId().getName().equals(target.getName())) {
			// we found it
			if (commit instanceof DepthWalk.Commit) {
			    DepthWalk.Commit dwc = (DepthWalk.Commit) commit;
			    return Optional.of(Integer.valueOf(dwc.getDepth()));
			} else {
			    throw new IllegalStateException(String.format("implementation of %s or jgit internal has been incorrectly changed", DepthWalkDistanceCalculator.class.getSimpleName()));
			}
		    }
		}
	    } catch (IOException ignore) {
		ignore.printStackTrace();
	    } finally {
		if (walk != null) {
		    walk.dispose();
		    walk.close();
		}
	    }
	    return Optional.empty();
	}
```

Again, I don't know if it is the correct thing to do, but it fixes my issue. Could you please take a look at this and send me a feedback.
Thank you!

**Comment by McFoggy** [comment]
@mbrasil what you describe is not a bug it is the way jgitver works.
jgitver does not try all the branches to find tags but only the tags reachable from `HEAD`.
