### ISSUE TITLE
project.version is undefined

### ISSUE THREAD

**Issue by HEm3R** [jgitver/jgitver#77]
Hi,

I have simple project configured by docu:

```
plugins {
    id 'fr.brouillard.oss.gradle.jgitver' version '0.8.0'
}

println "current version: $version"
```

and it prints version as undefined: `current version: unspecified`.

It is problem when I need to distinguish between snapshot and release for publishing:

```
plugins {
    id 'maven-publish'
    id 'distribution'
    id 'fr.brouillard.oss.gradle.jgitver' version '0.8.0'
}

group = 'com.test'

jgitver {
  strategy 'MAVEN'
}

distributions {
    main {
        contents {
            from 'file.xml'
        }
    }
}

publishing {
    publications {
        distibution(MavenPublication) {
            artifact distZip
        }
    }

    repositories {
        maven {
            name 'libs'

            def repoUrl = 'http://artifactory'
            def snapshotsRepoUrl = "$repoUrl/snapshot"
            def releasesRepoUrl = "$repoUrl/release"
            url = version.toString().endsWith("-SNAPSHOT") ? snapshotsRepoUrl : releasesRepoUrl
        }
    }
}
```

As the version is undefined it always tries to publish `-SNAPSHOT` versions to repository for regular releases.

I have gradle `5.2.1`.

Is there any way how to force `version` to be set? I can access the version in `afterEvaluate`:

```
allprojects {
	project.afterEvaluate {
		println "${project.name}::${project.version}"
	}
}
```

Thanks!

**Comment by McFoggy** [comment]
> I can access the version in afterEvaluate

It is the lifecycle where jgitver hooks, see code [here](https://github.com/jgitver/gradle-jgitver-plugin/blob/master/src/main/java/fr/brouillard/oss/gradle/plugins/JGitverPlugin.java#L24).

So if you hook before jgitver enters the game then the version will not be set.

**Comment by HEm3R** [comment]
@McFoggy hm, I see.

So, is there any way how to request the version from jgitver before afterEvaluate to make the publishing work? :)

**Comment by McFoggy** [comment]
not that I am aware of.

I am not a gradle specialist, but can't you delay evaluation of the publishing stuff?

**Comment by HEm3R** [comment]
Ok, it looks it is possible (and works):

```
publishing {
    publications {
        distibution(MavenPublication) {
            artifact distZip
        }
    }

    repositories {
        maven {
            name 'libs'

            afterEvaluate {
                def repoUrl = 'http://artifactory'
                def snapshotsRepoUrl = "$repoUrl/snapshot"
                def releasesRepoUrl = "$repoUrl/release"
                url = version.toString().endsWith("-SNAPSHOT") ? snapshotsRepoUrl : releasesRepoUrl
            }
        }
    }
}
```

Thanks for your help @McFoggy.
