### ISSUE TITLE
Wrong calculation of commit distance

### ISSUE THREAD

**Issue by anessi** [jgitver/jgitver#82]
As discussed in https://gitter.im/jgitver/Lobby?at=5ca71a79f851ee043d659db4 there is a problem with the calculation of the commit distance if a feature branch is containing less commits than the main branch.

I tried to fix this with a pull request and it works fine for me, but I'm not a git expert and don't know if this is the ideal solution. All tests pass except 2, but they are not related to my changes.
Please also note that the branch still needs some cleanup as I included logging to see what's going on when traversing the revision. Please note that the logging makes it very slow, so I would change BigRepositoryWithMultiBranchesTest.NB_COMMITS_PER_BRANCH to some smaller number.
I can clean the logging up if you want, but feel free to do so yourself.

Changes: https://github.com/anessi/jgitver/pull/1

**Comment by anessi** [comment]
Would be great to get some feedback if my proposed approach is usable. Thx

**Comment by McFoggy** [comment]
@anessi I am looking into it this week.

Sorry for the delay I am switching to a new job and thus my focus for the past few weeks/months was not very OSS oriented.

**Comment by anessi** [comment]
Sure, no problem at all. Thanks for your support!

**Comment by McFoggy** [comment]
@anessi thank you for your contribution ; I have enhanced & merged your proposals in `0.11.0`

**Comment by anessi** [comment]
Great - thanks! Do you plan to release a new version of the gradle plugin with the latest changes soon? It would be nice if an additional property is added to set the jgitver.calculator.kind

**Comment by McFoggy** [comment]
@anessi done in gradle plugin 0.9.0

see https://github.com/jgitver/gradle-jgitver-plugin#configuration and the new configuration `distanceCalculatorKind `

maven plugin is not yet released

**Comment by anessi** [comment]
Wow - that was quick! I will upgrade some projects and see how this goes. thanks a lot

**Comment by anessi** [comment]
I upgraded two projects now and found an issue with the current implementation. It seems that in some situation it's entering a loop. I only had this issue on one repository of the two I upgraded so far. Looks like it depends on how the branches are interconnected. I fixed this in PR #86.

Unfortunately I was not able to write a proper unit test to reproduce the issue (I tried quite hard 😄), so I extended the Scenarios class to allow to run 'integration' tests on a existing repo. An example test has been added, but disabled. Please see PR #87 

The last issue I noticed is related to the performance of the gradle plugin. We have one large multi-module project and the version calculation is currently executed for each (sub)module (e.g. 25 times in our case). As the version calculation is slower than before, this leads to a noticeable slowdown of build execution (10s in our case). I think this could be improved easily be executing the version calculation just once. If I find some time I will look into this.

**Comment by McFoggy** [comment]
Thanks I'll look at them this week.

**Comment by anessi** [comment]
I can also confirm that the latest version fixed in (https://github.com/jgitver/gradle-jgitver-plugin/issues/24) works of for our case as well.
