### ISSUE TITLE
Set strategy parameters from CLI

### ISSUE THREAD

**Issue by adovbnya** [jgitver/jgitver#91]
Is it possible to set strategy parameters using the CLI ?
For example, PATTERN strategy, according to [description](https://github.com/jgitver/jgitver/issues/33), uses `versionPattern` parameter, but how to set it from CLI (there is no description in README), or is it impossible for current version of `jgitver` (`v0.11.2`)?

**Comment by jack-r-warren** [comment]
From [this file](https://github.com/jgitver/jgitver/blob/master/src/main/java/fr/brouillard/oss/jgitver/cli/Options.java), it doesn’t look like that’s possible. I can look into adding it.

**Comment by McFoggy** [comment]
indeed it is not handled from CLI
