### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by Zomzog** [jgitver/jgitver#97]
Hi @McFoggy ,

We need to use the new configuration from #92 with Gradle (https://github.com/jgitver/gradle-jgitver-plugin/pull/27) and Maven (https://github.com/jgitver/jgitver-maven-plugin/pull/122) plugins.

But I'm not sure of what part can be done by someone else in the process https://github.com/jgitver/jgitver#release 

Thanks.

**Comment by McFoggy** [comment]
Thanks for your interest & efforts in the project. I'll perform a release and integrate the PRs later this week.

**Comment by McFoggy** [comment]
FYI I faced issues during the week-end with signing the tag for release. I need to understand what is blocking me at the moment.

Sorry for the delay.

**Comment by Zomzog** [comment]
Ok. Thanks for the info.

**Comment by McFoggy** [comment]
I finally resolved my GPG issues and performed release `0.12.0`

I'll continue with maven & gradle plugins later on

**Comment by Zomzog** [comment]
Thank @McFoggy 
I've updated my PR on maven and gralde plugins with the new version.
